version: '3.8'

services:
  userservice:
    image: khshanovskyi/mockuserservice:latest
    ports:
      - "8006:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - GENERATE_USERS=true
      - USER_COUNT=1000
    volumes:
      - ./data:/app/data
  
  mcp-server:
    build: ./mcp_server
    ports:
      - "8005:8005"
    environment:
      - USERS_MANAGEMENT_SERVICE_URL=http://userservice:8000
    depends_on:
      - userservice
